# Generated by Django 5.2b1 on 2025-03-05 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=30, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(verbose_name="Response")),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Max Balance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menus",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "menu_id",
                        "item_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("menu_id", models.PositiveIntegerField(verbose_name="Menu ID")),
                ("item_id", models.CharField(max_length=20, verbose_name="Item Name")),
                ("info", models.TextField(verbose_name="Nutritional Info")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Cost"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Item Name",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Amount Purchased"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Balance"
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="diningHall.mealplan",
                        verbose_name="Meal Plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=20, verbose_name="Item Name")),
                ("dop", models.DateField(verbose_name="Date of Purchase")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Cost"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diningHall.student",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
    ]
